# Change these first
owner: klutzybubbles # Your GitHub organization or username, where this repository lives
repo: klutzybubbles-status # The name of this repository

sites:
  - name: Baseline
    url: https://www.google.com
    showAverageResponseTime: false
  - name: AWX
    url: http://awx.klutzybubbles.me
    __dangerous__insecure: true
    showAverageResponseTime: false
  - name: GorillaToes Minecraft
    url: https://mc.gorillatoes.net
    __dangerous__insecure: true
    showAverageResponseTime: false
  - name: Paperless
    url: https://paperless.klutzybubbles.me
    __dangerous__insecure: true
    showAverageResponseTime: false
  - name: Gitea
    url: http://git.klutzybubbles.me
    __dangerous__insecure: true
    showAverageResponseTime: false

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.klutzybubbles.me
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: KlutzyBubbles Service Status
  introTitle: "Services hosted by KlutzyBubbles"
  introMessage: Wont always be online sorry
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: dark
workflowSchedule:
  uptime: "*/30 * * * *"
  

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
